env: TRAVIS_CI=true
language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  - sudo apt-get install -y libsubunit-dev
  # for curl
  - sudo apt-get install -y libcurl4-openssl-dev
  # for static code analysis
  # - sudo apt-get install -y cppcheck rats
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone --depth 10 https://github.com/proftpd/proftpd.git
  - mkdir -p proftpd/contrib/mod_conf_url/
  - cp *.[ch] proftpd/contrib/mod_conf_url/
  - cp mod_conf_url.* proftpd/contrib/mod_conf_url/
  - cp Makefile.in proftpd/contrib/mod_conf_url/
  - cp config* proftpd/contrib/mod_conf_url/
  - cp install-sh proftpd/contrib/mod_conf_url/
  - cp -R t/ proftpd/contrib/mod_conf_url/t/
  - cd proftpd
  - ./configure LIBS='-lm -lsubunit -lrt -pthread' --enable-devel=coverage --enable-dso --enable-tests --with-shared=mod_conf_url
  - make
  - make clean
  - ./configure LIBS='-lm -lsubunit -lrt -pthread' --enable-devel=coverage --enable-tests --with-modules=mod_conf_url
  - make
